server:
  port: 9999

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9080/eureka/,http://${eureka.instance.hostname}:9091/eureka/
spring:
  application:
    name: turbine
hystrix:
  dashboard:
    proxy-stream-allow-list: 127.0.0.1
turbine:
  app-config: user
  cluster-name-expression: "'default'"
management:
  endpoints:
    web:
      exposure:
        include: "*"

