server:
  port: 9090

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9080/eureka/,http://${eureka.instance.hostname}:9091/eureka/
spring:
  application:
    name: user
feign:
  hystrix:
    enabled: true
logging:
  level:
    com.shbh.user.feign.BillFeign: debug