server:
  port: 9090

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9080/eureka/,http://${eureka.instance.hostname}:9091/eureka/
spring:
  application:
    name: sentinel
feign:
  hystrix:
    enabled: true
logging:
  level:
    com.shbh.user.feign.BillFeign: debug
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      circuitBreaker:
        requestVolumeThreshold: 10
        sleepWindowInMilliseconds: 10000
        errorThresholdPercentage: 50
  dashboard:
    proxy-stream-allow-list: 127.0.0.1
management:
  endpoints:
    web:
      exposure:
        include: "*"