server:
  port: 9010

eureka:
  instance:
    hostname: 39.105.29.35
    prefer-ip-address: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9080/eureka/,http://${eureka.instance.hostname}:9081/eureka/
tx-lcn:
  client:
    manager-address: 39.105.29.35:8070
  manager:
    dtx-time: 600000
spring:
  cloud:
    sentinel:
      web-context-unify: false
      transport:
        dashboard: localhost:7070
      eager: true
      datasource:
        ds1:
          file:
            file: classpath:flowrule.json
            data-type: json
            rule-type: flow
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.126.61:3306/4h8h?useUnicode=true&characterEncoding=UTF-8&ENGINE=InnoDB
    username: root
    password: mylord
  application:
    name: users
  zipkin:
    base-url: http://127.0.0.1:9411/ #http发送
    sender:
      #type: web
      type: rabbit
    sleuth:
      sampler:
        probability: 1
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      listener: # 这里配置了重试策略
        direct:
          retry:
            enabled: true
        simple:
          etry:
            enabled: true
#feign:
#  hystrix:
#    enabled: true
#logging:
#  level:
#    com.shbh.user.feign.BillFeign: debug
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000
#      circuitBreaker:
#        requestVolumeThreshold: 10
#        sleepWindowInMilliseconds: 10000
#        errorThresholdPercentage: 50
#  dashboard:
#    proxy-stream-allow-list: 127.0.0.1
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"