server:
  port: 9080
eureka:
  instance:
    hostname: 39.105.29.35
    prefer-ip-address: true         #是否优先使用ip
  client:
    registerWithEureka: true  #是否注册自己
    fetchRegistry: true  #是否获取服务
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9081/eureka/
spring:
  application:
    name: eureka1