server:
  port: 9060
spring:
  application:
    name: gateway
  cloud:
    gateway:
      #手动配置路由
      routes:
        - id: users
          #uri: http://127.0.0.1:9090/
          uri: lb://users
          predicates:
            - Path=/users/**
          filters:
            #- StripPrefix=1
            #- name: RequestRateLimiter
            #args:
            #redis-rate-limiter.replenishRate: 1
            #redis-rate-limiter.burstCapacity: 2
            #key-resolver: "#{@pathKeyResolver}"
            - RewritePath=/users/(?<segment>.*),/$\{segment}
        - id: admin
          #uri: http://127.0.0.1:9090/
          uri: lb://admin
          predicates:
            - Path=/admin/**
          filters:
            #- StripPrefix=1
            #- name: RequestRateLimiter
              #args:
                #redis-rate-limiter.replenishRate: 1
                #redis-rate-limiter.burstCapacity: 2
                #key-resolver: "#{@pathKeyResolver}"
            - RewritePath=/admin/(?<segment>.*),/$\{segment}
      #根据服务名自动转发
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  redis:
    host: 39.105.29.35
    port: 6379
    database: 0
  zipkin:
    #base-url: http://127.0.0.1:9411/ #http发送
    sender:
      #type: web
      type: rabbit
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener: # 这里配置了重试策略
      direct:
        retry:
          enabled: true
      simple:
        etry:
          enabled: true
eureka:
  instance:
    hostname: 39.105.29.35
    prefer-ip-address: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9080/eureka/,http://${eureka.instance.hostname}:9091/eureka/
logging:
  level:
    root: info
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG
