server:
  port: 9050
eureka:
  instance:
    hostname: 39.105.29.35
    prefer-ip-address: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9080/eureka/,http://${eureka.instance.hostname}:9081/eureka/
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:7070
      eager: true
      datasource:
        ds1:
          file:
            file: classpath:flowrule.json
            data-type: json
            rule-type: flow
      web-context-unify: false
  application:
    name: sentinel
  zipkin:
    base-url: http://127.0.0.1:9411/ #http发送
    sender:
      #type: web
      type: rabbit
    sleuth:
      sampler:
        probability: 1
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      listener: # 这里配置了重试策略
        direct:
          retry:
            enabled: true
        simple:
          etry:
            enabled: true
feign:
  sentinel:
    enabled: true