server:
  port: 9050
eureka:
  instance:
    hostname: 39.105.29.35
    prefer-ip-address: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9080/eureka/,http://${eureka.instance.hostname}:9081/eureka/
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:7070
      eager: true
      datasource:
        ds1:
          file:
            file: classpath:flowrule.json
            data-type: json
            rule-type: flow
  application:
    name: sentinel
feign:
  sentinel:
    enabled: true