server:
  port: 9093
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9080/eureka/,http://${eureka.instance.hostname}:9081/eureka/
spring:
  application:
    name: bill